id: IA133BA59
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T08:29:54+00:00'
last_modified: '2022-06-08T03:20:16.947495+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7910
  title: མཐུན་ལུང་བཤད་གྲྭའི་སློབ་དེབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '7701':
      image_group_id: I3CN7912
      title: ''
      total_pages: 301
      order: 1
      base_file: 7701.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
