id: P005473
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN7910
  title: མཐུན་ལུང་བཤད་གྲྭའི་སློབ་དེབ།
  author: ''
  volumes:
    e4cf29aa14d84dd6b3b7794e213d693c:
      image_group_id: I3CN7912
      title: ''
      volume_number: 1
      total_pages: 301
      base_file: v001.txt
